language: python

matrix:
  include:
    - name: "Unit testing"
      os: linux
      dist: xenial
      python: "3.7"
      before_install:
        - sudo apt-get install -y gnupg
        - pip3 install codecov
      addons:
        sonarcloud:
          organization: "skvl-github"
          token:
            secure: "$SONAR_TOKEN"
      install:
        - pip3 install pipenv
        - pipenv install -d -v
      script:
        - coverage run ./setup.py test
        - coverage xml -i -o coverage.xml
        - sonar-scanner -Dsonar.python.coverage.reportPath=./coverage.xml
      after_success:
        - codecov

    - name: "Linux"
      os: linux
      dist: xenial
      python: "3.7"
      install:
        - python3 ./setup.py install
      script:
        - gpm -p 123 encrypt
        - gpm -p 123 decrypt

    - name: "Windows"
      os: windows
      language: shell
      before_install:
        - choco install -y python --version 3.7.3
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      install:
        - python ./setup.py install
      script:
        - gpm -p 123 encrypt
        - gpm -p 123 decrypt

    - name: "OS X"
      os: osx
      osx_image: xcode10.2
      language: shell
      update: true
      install:
        - python3 ./setup.py install
      script:
        - gpm -p 123 encrypt
        - gpm -p 123 decrypt
