dist: xenial
language: python
python:
  - "3.7"
before_install:
  - sudo apt-get install -y gnupg
install:
  - pip install pipenv
  - pipenv install -d -v

matrix:
  include:

  - env:
    - TEST="unittest"
    script:
        - python setup.py test

  # A workaround for Travis CI. Remove later.
  - env:
    - TEST="typing"
    script:
      - mypy git_privacy_manager

  - env:
    - TEST="SonarCloud"
    addons:
      sonarcloud:
        organization: "skvl-github"
        token:
          secure: "$SONAR_TOKEN"
    script:
      - sonar-scanner

  - env:
    - TEST="codecov"
    install:
      - pip install pipenv
      - pipenv install -d -v
      - pip install codecov
    script:
      - coverage run ./setup.py test
    after_success:
      - codecov
